### ISSUE TITLE
Models return negative score

### ISSUE THREAD

**Issue by Tranquangdai** [o19s/elasticsearch-learning-to-rank#121]
Currently, I’m using your plugin Learning to rank in order to improve our customer’s search experience. According to your documents, Learning to rank (LTR) plugin is currently supporting 2 algorithms, which is Ranklib(in Java) and Xgboost(in Python). I’ve found that your plugin is very great and it helps improve our search engine.
However, I have a few concerns regarded with the way ElasticSearch use LTR plugin to rescore the final model:
1. I’ve tried to use pointwise approach to solve Learning to rank problem, which use xgboost as a learning algorithm and “binary:logistic” as a learning objective. According to this, every final data point that we’re trying to rerank will get a score as probability output by xgboost model, this score lies somewhere between 0 and 1. 
However, when inspecting the xgboost’s score in production, I’ve found that many of them have their score out of the range that was expected above; some of them even get negative score (-6.29 for instance). We would like to know more why this is happening?
2. I’ve seen that xgboost also support “pairwise” learning to rank. So I wonder if I could integrate this model with ElasticSearch LTR plugin?

**Comment by softwaredoug** [comment]
@Tranquangdai is there any way you can create a model that demonstrates the issue with your first bullet? Perhaps using the movie data in the demo part of this repo?

I do not know enough about 2, but @ebernhardson and his colleagues at Wikimedia use XGBoost to build pair-wise gradient boosting models I believe. Perhaps they could point you in the right direction.

**Comment by Tranquangdai** [comment]
Hi softwaredoug.
Thanks for your quick response to my questions.
For the first bullet: "Xgboost model return negative score", I've demonstrated this point with a code snippet which shows that by using xgboost with "objective: binary:logistic" always return a score (which is a probability) bound by 0 and 1. But, strangely, the models after uploading to elastic search gave negative score. 
Also, note that the data used for training model is a little different from what's in the demo: The dependent variable instead of a continuous score (relevance judgments made by users watching a movie like in the demo), I use 1 and 0 as an indicator of click or not click. So I think it's best to model it as a pointwise Classification problem where score is a probability of a query being clicked.
I've made a github repo to further explain my point, please reference it if needed.
[ElasticSearch_demo](https://github.com/Tranquangdai/ES_demo/blob/master/demo%20notebook.ipynb)

**Comment by ebernhardson** [comment]
The tree evaluation in elasticsearch ltr only emits the raw scores from summing up the individual trees, in xgboost some of the objectives have their own post-processing steps which we don't implement.

For binary:logistic that is defined at:
https://github.com/dmlc/xgboost/blob/master/src/objective/regression_obj.cc#L177-L179
in the [LogisticClassification](https://github.com/dmlc/xgboost/blob/master/src/objective/regression_obj.cc#L58) class which extends from [LogisticRegression](https://github.com/dmlc/xgboost/blob/master/src/objective/regression_obj.cc#L36-L56) and implements PredTransform using [common:Sigmoid](https://github.com/dmlc/xgboost/blob/24f527a1c095b24115dc5d54ad35cc25d3bc3032/src/common/math.h#L23-L25).

Because sigmoids preserve the ordering of their input, simply mapping it to a bounded space, there should be no ranking difference between using the raw predictions and transforming that prediction. If it's particularly important to have the bound for other reasons you should be able to use a script_score in elasticsearch to do the transformation.

**Comment by Tranquangdai** [comment]
I try to rescore the raw score output by xgboost with sigmoid function: 1/(1 + exp(-x)), but as far as I know, ES doesn't currently support EXP function, so how can I overcome this issue with ES?

**Comment by ebernhardson** [comment]
It looks like you can Math.pow?
```
{
    "_source": false,
    "size": 1
    "query": {
        "function_score": {
            "query": { "match_all": {} },
            "script_score": {
                "script": {
                    "inline": "1 / (1 + Math.pow(2.71828, -_score))"
                }
            }
        }
    },
}  
```

This gets me back 0.731 as the score, which is correct for 1 as the input to the sigmoid.

**Comment by Tranquangdai** [comment]
thanks a lot @ebernhardson !

**Comment by khaihuynh92** [comment]
The same case, for me I modified the _score of LTR by a script_score:
```
"rescore": {
    "window_size": 24,
    "query": {
      "rescore_query": {
        "function_score": {
          "query": {
            "sltr": {
              "params": {
                "keywords": "iphone"
              },
              "model": "my_xgboost_model"
            }
          },
          "script_score": {
            "script": {
              "source": "1.0 / (1.0 + Math.exp(0-_score))"
            }
          }
        }
      },
      "query_weight": 1,
      "rescore_query_weight": 100
    }
  }
```

**Comment by manu-dikzit** [comment]
@khaihuynh92 

I needed to add an additional parameter to the rescore_query.function_score object for this to have the expected behaviour

``` 
"rescore": {
    "window_size": 24,
    "query": {
      "rescore_query": {
        "function_score": {
          "boost_mode": "replace",
          "query": {
            "sltr": {
              "params": {
                "keywords": "iphone"
              },
              "model": "my_xgboost_model"
            }
          },
          "script_score": {
            "script": {
              "source": "1.0 / (1.0 + Math.exp(0-_score))"
            }
          }
        }
      },
      "query_weight": 1,
      "rescore_query_weight": 100
    }
  }
```
If we don't supply `boost_mode:"replace"` ,it multiplies the successive scores.

**Comment by davefernig** [comment]
Reopening this issue to address logging.

The script score sigmoid works, but it breaks the logger. Suppose I point `ltr_log` at the first rescore block:
```json
"ext": {
  "ltr_log": {
    "log_specs": {
      "name": "ltr_feature_scores",
      "rescore_index": 0
    }
  }
}
```

And then I modify that block to be a `function_score` that implements a sigmoid transform after inference, as proposed by [ebernhardson](https://github.com/ebernhardson). On execution, I get the following error:
```json
"failures": [
  {
    "reason": {
      "type": "illegal_argument_exception",
      "reason": "Expected a [sltr] query but found a [FunctionScoreQuery] at index [0]"
    }
  }
]
```
I've tried naming the inner sltr query and using `named_query` in the logger (instead of a rescore index), but this doesn't seem to work either:
```json
"failures": [
  {
    "reason": {
      "type": "illegal_argument_exception",
      "reason": "No query named [sltr_inference] found"
    }
  }
]
```

Any ideas on how to proceed? The end goal here is to achieve both:
1. A sigmoid transform on my sltr scores
2. Logging during inference, so that I don't have to do two forward passes

**Comment by davefernig** [comment]
Update: An alternative way to achieve this behaviour (which would require a PR) would be to let the user specify the normalizer applied to their model. Right now, the normalizer is set automatically as a function of the objective on which the model was trained. For rank:pairwise, it is set to noop ([source](https://github.com/o19s/elasticsearch-learning-to-rank/blob/d5c5b9f450a5ae921c671f4a42fc4a59694e6149/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostJsonParser.java#L123)). If the `_createmodel` endpoint exposed a `normalizer` argument, this could be used to combine a pairwise ranker with sigmoid-squashed outputs (without any clever script-scoring).
