### ISSUE TITLE
Circuit Breaking Exception on using painless scripting

### ISSUE THREAD

**Issue by sasankvemuri** [o19s/elasticsearch-learning-to-rank#138]
When I try to run a query in a loop via python, it throws me this error

{'error': {'root_cause': [{'type': 'circuit_breaking_exception', 'reason': '[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting', 'bytes_wanted': 0, 'bytes_limit': 0}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'lab', 'node': 'mJfiCkmrTMOy8R3J2hEwFw', 'reason': {'type': 'general_script_exception', 'reason': "Failed to compile inline script [def factor = 157771563; def cur = 0; cur = (factor - doc['BS_START'].value); if (cur < 0) { cur = cur * -1 } else { cur = cur}] using lang [painless]", 'caused_by': {'type': 'circuit_breaking_exception', 'reason': '[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting', 'bytes_wanted': 0, 'bytes_limit': 0}}}]}, 'status': 500}

The query is basically to push in multiple coordinates and try to find nearest value in corresponding table. I have used painless scripting for achieving this and it bottlenecks at 75/5m

I tried adding the following line to yml file and it just does not make any difference

script.max_compilations_per_minute: 10000

Can someone sort this.

P.S: ES 6.2

**Comment by ebernhardson** [comment]
Not sure about 6.2, but i run 5.5 and `script.max_compilations_per_minute` is sufficient to work around this. Anyone on 6.x that can try it out?

**Comment by nomoa** [comment]
Could you share your painless script?
The plugin will apply a template to generate the elasticsearch query. If the generated query is a script (e.g. painless) whose params are transcluded by the plugin then you may hit this circuit breaker.

This is because the script as seen by elasticsearch is never the same and can't be cached by the plainless script engine.

In other words If your painless script directly references the variables in its source then you should try to extract them as script params.

A script that may hit the circuit breaker:
```json
                    "script" : {
                        "source": "doc['num1'].value > {{feature_param}}",
                        "lang": "painless"
                     }
```

A script that can be [cached](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-query.html#_custom_parameters):
```json
                    "script" : {
                        "source": "doc['num1'].value > params.param1",
                        "lang": "painless",
                        "params" : {
                            "param1" : {{feature_param}}
                        }
                     }
```

**Comment by sasankvemuri** [comment]
Yes you are absolutely right. I went through tonns of posts before figuring it out and used a parameter to accept variable instead of using it with the script. Now it works like a charm.

**Comment by nomoa** [comment]
Thanks for the feedback, I'm closing this issue as it's not directly related to the plugin. Perhaps we could improve the doc to add a note about this.
