### ISSUE TITLE
Find a strategy to upgrade the store indices when their mapping/settings become incompatible with future elastic version 

### ISSUE THREAD

**Issue by nomoa** [o19s/elasticsearch-learning-to-rank#144]
The plugin uses a normal elasticsearch index to store its components.
It's likely that in the future some bits of the mapping/settings become incompatible with future elasticsearch version.
The plugin should provide a sane method to upgrade its indices so that users don't have to delete/reinsert their data prior to upgrading.
We should follow what will be done for the .`tasks` index upstream as it'll share the same problem.

**Comment by softwaredoug** [comment]
I'd be curious if this has burned anyone as we've gone from 5.x to 7.x now. Or is it the case that teams recreate their feature stores/models after an upgrade?

**Comment by umeshdangat** [comment]
At Yelp we typically recreate the feature stores/models post the upgrade.

**Comment by softwaredoug** [comment]
That seems like the best thing to do, instead of worrying about index migrations, should we recommend this? 

Or is it possible an upgrade would occur and we should at least output an error?

Seems like your feature store/etc would be part of your code in version control, and Elastic LTR shouldn't be the only system of record for your features etc

**Comment by softwaredoug** [comment]
I'm going to close this as wontfix, we can reopen. But I think the official line is be able to recreate the feature store, etc post upgrade instead of trying to carry it forward...
