### ISSUE TITLE
No Replicas for  Feature Stores

### ISSUE THREAD

**Issue by dacox** [o19s/elasticsearch-learning-to-rank#171]
I noticed that when you create a _feature store_, there are no replicas for that index, and there doesn't seem to be any way to configure that through the API.
```sh
green  open .ltrstore       LS97uWNqQJ-QLY1lHnmbvQ 1 0    3 0 11.2kb 11.2kb
```
Was this intentional? We will be storing everything required to recreate the _feature store_, but am curious as to why this decision was made.

We typically do rolling updates of our production cluster, and would prefer to not have to recreate these stores whenever that happens.

If there is an open issue feel free to point me in that direction.

Cheers

**Comment by nomoa** [comment]
The feature stores should be created with [auto_expand_replicas](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings) set to `0-2`. So unless there's something broken in the plugin I suppose you created the store on a single node cluster. Basically if you attach another node to the cluster it should spawn a new replica automatically (up to 2 replicas so that in the end you'll have 3 copies of the feature stores on clusters with 3 or more nodes).
If you worked on a multi-node cluster then there is something wrong in the plugin indeed.

**Comment by dacox** [comment]
@nomoa D'oh! I jumped the gun - I was definitely testing it out on a single node cluster. Thanks!
