### ISSUE TITLE
Add HTTP based ranker

### ISSUE THREAD

**Issue by pradithya** [o19s/elasticsearch-learning-to-rank#267]
I am new to ES LTR and thinking of adding a ranker which call to a model deployed as web services through HTTP (for example TF Serving but not limited to it). 
After having short skimming through the code base, it seems that in order to do that I would have to implement the ranker and satisfy `LtrRanker` interface as well as the associated `FeatureVector`. Am I right on this? Is there any other part that I need to do?

**Comment by nomoa** [comment]
Beware that today LtrRanker will score one doc at a time and thus would make a blocking http per scored document. I'm afraid that the perf would not be acceptable without having a way to do bulk scoring with the plugin.

I'm happy to resurrect https://github.com/o19s/elasticsearch-learning-to-rank/tree/custom_rescore_context which introduces [BulkLtrRanker](https://github.com/o19s/elasticsearch-learning-to-rank/blob/custom_rescore_context/src/main/java/com/o19s/es/ltr/ranker/BulkLtrRanker.java)  and [FeatureMatrix](https://github.com/o19s/elasticsearch-learning-to-rank/blob/custom_rescore_context/src/main/java/com/o19s/es/ltr/ranker/FeatureMatrix.java) that could be implemented to rank multiple docs at once.

Another semi-related feature that would be interesting is to make this plugin an [extensible plugin](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/plugins/ExtensiblePlugin.java) making ranker implementations discover-able.

**Comment by softwaredoug** [comment]
@pradithya I think this could be very hard to do. I think I would ask a specific design proposal that would deal with @nomoa's concerns. On first blush, thinking of doing HTTP calls out from the ranker, I'd think it'd be more efficient to have a system out side of ES do the work.

I think for tensor flow, we'd prefer to figure out how to us TF more natively on the ES cluster rather than using TF Serving... 

So going to close with 'wont fix' but don't hesitate to work on some idea or dig deeper into a proposal and we can give you feedback
