### ISSUE TITLE
Feature Normalization

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#286]
I was recently using RankSVM with Solr, and realized through that process how crucial feature normalization is with SVMs. I wondered about the Elastic LTR plugin, and realized that we probably need to add optional, per-feature normalization.

In a perfect world we could 'log' normalized features. Then train using the same feature normalization that is used during model evaluation in the plugin.

However, that's probably not possible as most normalization methods are either min/max (what's the min / max value for this feature) or are based on mean / std deviation of the feature. So you need to see the full range of possible feature values when training. This IS feasible when you're training over the whole set. 

Still these are per-feature characteristics, so it would seem that either the model or the features set needs to associate a feature with a normalizer... and that this could be updated via a CRUD API

**Comment by nathancday** [comment]
I've always been a fan of normalizing features for use in SVMs, b/c of the need for similar scales to measure feature importance fairly. This isn't as big of a deal in decision trees because features are often considered independently.

It looks like the ability to normalize is bakes into [RankLib's -norm flag](https://sourceforge.net/p/lemur/wiki/RankLib%20How%20to%20use/) so exposing it could be done. But RankLib doesn't seem to have an SVM model, just nets and trees so there might not be a big performance bump from feature normalization.

**Comment by softwaredoug** [comment]
My proposal would be that on model creation, we specify how features ought to be normalized. Then this is stored as a property of the model. Then features would be preprocessed before being passed to the model.

I would propose to NOT make it a property of the feature set, as it seems to be a choice often made at model training. We may log features, and from that feature set we perform different normalizations appropriate for that family of models.

(This appears to be what Solr does, where normalizers are properties of the model)
