### ISSUE TITLE
How much increase is needed for hosting model of size X 

### ISSUE THREAD

**Issue by lasagar** [o19s/elasticsearch-learning-to-rank#311]
How much more RAM should we plan to add on coordinator nodes for a model of size let's say ~2MB than the usual setup of elastic search.  Are there any recommendations?

**Comment by nathancday** [comment]
I'm going to close this issue, because it's not related to a problem with the plugin per say. It might be worth asking the #es-learn-to-rank channel over on [the Relevancy slack](https://join.slack.com/t/relevancy/shared_invite/zt-cinrruqs-5i7pBXbbiH8J6Y~DLxryFg). I'm sure other people would be interested when you are ready share your findings.
