### ISSUE TITLE
`min_raw_df` returns `Float.MAX_VALUE` for non-vocabulary words

### ISSUE THREAD

**Issue by wxd** [o19s/elasticsearch-learning-to-rank#356]
ElasticSearch version: `7.8.0` or `7.9.0` (in Docker)
Plugin version: `ltr-1.3.0-es7.8.0` or `ltr-plugin-v1.5.0-es7.9.0`

Are there any solutions/workarounds?

#### `min_raw_df`
```json
{"query": {"match_explorer": {"type": "min_raw_df", "query": {"match": {"text": "xxx"}}}}}
```

```json
{"hits": {"max_score": 3.4028235E38}}
```

#### `max_raw_df`
```json
{"query": {"match_explorer": {"type": "max_raw_df", "query": {"match": {"text": "xxx"}}}}}
```

```json
{"hits": {"max_score": 0.0}}
```

**Comment by worleydl** [comment]
Hello,

This looks like a bug.  I will test this week and let you know.

**Comment by worleydl** [comment]
Sorry for the wait, this will be fixed with PR #378

**Comment by worleydl** [comment]
Well it's partially fixed, I think collection stats are okay but document specific still needs some work.  `min_raw_tp` for example is still surfacing the behavior.

**Comment by worleydl** [comment]
After testing some more the doc specific stats have the following behaviors:
- If the query has no vocab words a value of 0 will be returned
- If the query has a mix of vocab and non, the non-vocabulary words will be excluded from the statistics.  This means a min(vocabWord, nonVocabWord) will always return the vocabWord and never 0.

This is due to the internal design of match explorer query.  From testing the term stat query things behave a little more predictably at the cost of some performance.  For now I think this particular issue is solved.
