### ISSUE TITLE
Does Ranklib2.16 contains the LR(Logistic Regression) model?

### ISSUE THREAD

**Issue by yzc1103** [o19s/elasticsearch-learning-to-rank#393]
According the link provided in the readme documentation of https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_7_6_2, I downloaded ranklib2.16 and found that only 8 models were included(as described in the ranklib2.16 introduction documentation linked to https://sourceforge.net/projects/lemur/files/lemur/RankLib-2.16/). However, the 9th model LR was used in the current https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_7_6_2/demo/train.py code. 
So I'm confused about this situation. Can anyone answer that question?

**Comment by nathancday** [comment]
Linear regression (not Logistic regression) was supported in past versions of Ranklib. It looks like it was dropped sometime before 2.16, which came out earlier this year.

We have a hardened fork of Ranklib, called [RankMcRankface](https://github.com/o19s/RankyMcRankFace) which still have linear regression as a model option. This is what the notebook code you referenced uses instead of Ranklib directly from SourceForge.
