### ISSUE TITLE
How to include categorical features in feature set

### ISSUE THREAD

**Issue by meg261995** [o19s/elasticsearch-learning-to-rank#461]
I have 3 features in my feature set, 2 are numerical and the other is categorical which has around 100 unique categories. I have included the numerical features like below and I am not sure how to include the cat feature. If I encode it and include in the below format I am guessing the model would treat it as a numerical feature which I do not want. Any help here please
**{
"validation": { "index": "my-index" },
  "featureset": {  "features": [
                                              {
                                                "name": "feat1",
                                                "template": {  "function_score": {  "field_value_factor": { "field": "feat1",  "missing":0   }, 
                                                                                                      "query": { "match_all": { } } }  } },
                                              {
                                                "name": "feat2",
                                                "template": {  "function_score": { "field_value_factor": { "field": "feat2",   "missing":0  },
                                                                                                "query": { "match_all": { } } }}
      }**

**Comment by meg261995** [comment]
The reason to include this is because I do not want the model to rank 2 documents of the same category one after the other.. The training set is also provided in the same way .. So make to the model learn this I want to include this categorical feature.

**Comment by nathancday** [comment]
small world moment here: https://stackoverflow.com/questions/75958254/including-categorical-features-in-elasticsearch-ltr, but I still think one-hot encoding is the path forward here. This notebook has an example with a two category feature (is a movie genre 'Drama' or 'Science Fiction' : https://github.com/o19s/hello-ltr/blob/main/notebooks/elasticsearch/tmdb/tale-of-two-queries%20(ES).ipynb

**Comment by meg261995** [comment]
Haha that's me only even there :) Wanted to make sure I get a reply soon so just posted on both platforms..

**Comment by mich123prem** [comment]
Hi!
I think this is interesting. I've been following the code of the "tale of two queries(ES)" example, and Im trying to figure out the following:
In the date_genre_judgments.py - file, the synthesize() function:

Seems the function only looks for the applicable genre value in the first value of the genres-field,
Is the genres list assumed to be sorted by the "importance" of the genres as appearing in the list, so that a list ["Drama", "Scince Fiction", "Comedy"] Would imply the main genre of the movie is "Drama"?
Or should the function open for "Drama" anywhere in the list?

Michael
Michael
