### ISSUE TITLE
Recent versions are not published to Maven repository

### ISSUE THREAD

**Issue by shinry0** [o19s/elasticsearch-learning-to-rank#475]
Even though the publishing step in GHA workflow appears to have been successful, there have been no builds published to Maven Central repository since v1.5.8-es8.6.2. Do you maintainers have knowledge of the cause of this? 

We want to use the latest version, so it would be nice to have it available in the repository.

https://central.sonatype.com/artifact/com.o19s/elasticsearch-learning-to-rank
https://mvnrepository.com/artifact/com.o19s/elasticsearch-learning-to-rank

![image](https://github.com/o19s/elasticsearch-learning-to-rank/assets/60764129/d682aa17-ab6c-4e4c-bd38-7b560c90533f)

**Comment by wrigleyDan** [comment]
Finally, we can close this one out.
Due to various circumstances, it took us a while to figure out what was going on in the background to prevent releases from being published to Maven repository. 
We fixed it, and the last version is now published.
Thanks for your patience.

We're seeing it here: https://central.sonatype.com/artifact/com.o19s/elasticsearch-learning-to-rank
And we expect it to be available here as well soon once Maven picks things up: https://mvnrepository.com/artifact/com.o19s/elasticsearch-learning-to-rank
