### ISSUE TITLE
Simplifying/hiding feature stores

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#68]
My first (perhaps incorrect) impression of feature stores is that they are an implementation detail most users would not think about. Are there cases where people would create more than one feature store? Or can a single feature store satisfy the vast majority of use cases?

Can we 
- Initialize the default feature store on plugin installation?
- Hide this implementation detail (don't document creating other feature stores?)

**Comment by ebernhardson** [comment]
at least for the wikimedia use case, we will have different feature stores for different sites. An example of where this is useful is our categories system. I have worked up examples where one-hot encoding category membership improves performance of the model, but the exact categories used are specialized to a single index.

**Comment by nomoa** [comment]
I thought about creating automatically feature stores but anticipated some issues I did not want to think about at the time of writing the initial code.
It'll require to dig into more details but creating an index at plugin initialization seems a bit hard because I'll probably encounter cluster issues, race conditions when multiple nodes start, etc...

One solution though would be to filter a set of REST request made to the /_ltr endpoint and create the index if it does not exists.
I need to dig into more details but that'll certainly involve yet another set transport actions which are mostly boiler plate code.

So to answer the issue, I agree that the default store creation should be transparent, concerning not documenting feature store I don't have strong opinions, the REST api is somewhat documented in the docs subfolder...

So when should we address this issue? I think I'd prefer to delay implementing it to when we'll have to add some code to update the feature index (i.e. for mapping changes).

**Comment by softwaredoug** [comment]
My other interest, aside from usability, is keeping things easy to upgrade to 6.0. So I think its simplest if people simply create the feature store. If we think of a better solution 

I think for documentation the best is to treat second feature stores as an advanced feature, and focus on feature sets/etc. I think the API assumes the default feature store, so that should help.
